---
title: "OpenData"
subtitle: "Quizz de la session 1"
author: "CEREMA Med > Mathieu Rajerison"
date: "<span style='font-size:0.5em;'>02/08/2018</span>"
output:
  xaringan::moon_reader:
    css: ["../css/my_css.css", "../css/my_css_session1.css", "default", "default-fonts"]
    seal: true
    lib_dir: libs
    self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: center, middle, inverse

# Questions

---

- Citez trois modes de transmission d'un message
- Comment appelle-t-on les "grands" de la donnée aux USA, et en Chine ?
- Qu'est-ce que la domotique ?
- Qu'est-ce qu'une ville intelligente ?
- Donnez trois élements d'une ville intelligente

---
- Quelle déclaration donne droit aux citoyens de demander un document à l'administration ? De quand date-t-elle ?
- Quel organisme a été créé en 2011 pour promouvoir l'ouverture des données publiques ?
- Quelle est la différence entre *data* et *opendata* ?
- Remplir les pointillés : production -> ... -> ... -> réutilisation
- Qu'est-ce qu'une licence ?

---
- Comment s'appelle le site national où trouver des données ouvertes ?
- Donnez le nom de deux organismes fournissant des données de référence
- Donnez le nom de trois sites OpenData
- Quel organisme dois-je contacter si mes données personnelles sont diffusées sur internet ?

---
- Comment est structuré un tableau de données ?
- Mettre dans un tableau les informations suivantes :
  - Aix en Provence, de code INSEE 13090, appartient au département des Bouches-du-Rhône, et compte 141438 habitants
  - Marseille compte 850726 habitants, du département des Bouches-du-Rhône, compte 850726 habitants. Son code INSEE est 13055
  - Nice compte 343304 habitants. Son code INSEE est 06088. Cette ville appartient au département des Alpes Maritimes.

---
- Que sont les données brutes ?
- Comment s'appellent des données détenues par le privé mais devant être rendues publiques ?
- Comment appelle-t-on des données fréquemment actualisées ? Et son contraire ?
- Comment appelle-t-on des données récentes ?

---
- Citez trois formats de fichiers de données, et les classer par ordre de préférence.
- Qu'est-ce qu'un système de gestion de base de données relationnelles ?
- Qu'est-ce qu'un identifiant ?
- Donnez deux raisons d'utiliser un identifiant